version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: php_apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - db
    command: bash -c "apt-get update && apt-get install -y libpng-dev libjpeg-dev && docker-php-ext-configure gd --with-jpeg && docker-php-ext-install gd mysqli && a2enmod rewrite && apache2-foreground"

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      # - db_data:/var/lib/mysql
      - ./src/mysql/demo.sql:/docker-entrypoint-initdb.d/demo.sql  # Montar el SQL para la inicialización
    ports:
      - "3306:3306"
    networks:
      - app-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - app-network
    depends_on:
      - db

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
